/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as CrewOpsRouteImport } from './routes/crew-ops'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MagHandleRouteImport } from './routes/mag.$handle'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewOpsRoute = CrewOpsRouteImport.update({
  id: '/crew-ops',
  path: '/crew-ops',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MagHandleRoute = MagHandleRouteImport.update({
  id: '/mag/$handle',
  path: '/mag/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crew-ops': typeof CrewOpsRoute
  '/shop': typeof ShopRoute
  '/mag/$handle': typeof MagHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crew-ops': typeof CrewOpsRoute
  '/shop': typeof ShopRoute
  '/mag/$handle': typeof MagHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crew-ops': typeof CrewOpsRoute
  '/shop': typeof ShopRoute
  '/mag/$handle': typeof MagHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crew-ops' | '/shop' | '/mag/$handle'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crew-ops' | '/shop' | '/mag/$handle'
  id: '__root__' | '/' | '/crew-ops' | '/shop' | '/mag/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrewOpsRoute: typeof CrewOpsRoute
  ShopRoute: typeof ShopRoute
  MagHandleRoute: typeof MagHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew-ops': {
      id: '/crew-ops'
      path: '/crew-ops'
      fullPath: '/crew-ops'
      preLoaderRoute: typeof CrewOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mag/$handle': {
      id: '/mag/$handle'
      path: '/mag/$handle'
      fullPath: '/mag/$handle'
      preLoaderRoute: typeof MagHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrewOpsRoute: CrewOpsRoute,
  ShopRoute: ShopRoute,
  MagHandleRoute: MagHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
